language: cpp
before_script:
        - mkdir build
        - cd build/
script:
        - cmake ..
        - make
        - ctest -VV
after_success:
        - cd ..
        - rm -rf build/
compiler:
        - clang
        - gcc
os:
        - linux
        - osx
